//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cjenik
    {
        public int cjenik_ID { get; set; }
        public System.DateTime datum_od { get; set; }
        public System.DateTime datum_do { get; set; }
        public double cjena { get; set; }
        public int resurs_ID { get; set; }
    
        public virtual Resurs Resurs { get; set; }
    }
}
