//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clanarina
    {
        public int clanarina_ID { get; set; }
        public System.DateTime datum_placanja { get; set; }
        public System.DateTime datum_placeno_do { get; set; }
        public int korisnik_ID { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
