//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dozvola
    {
        public int dozvola_ID { get; set; }
        public int tip_dozvole_ID { get; set; }
        public int korisnik_ID { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual TipDozvole TipDozvole { get; set; }
    }
}
