//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorivo
    {
        public Gorivo()
        {
            this.Zrakoplov = new HashSet<Zrakoplov>();
        }
    
        public int gorivo_ID { get; set; }
        public string gorivo_naziv { get; set; }
    
        public virtual ICollection<Zrakoplov> Zrakoplov { get; set; }
    }
}
