//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resurs
    {
        public Resurs()
        {
            this.Cjenik = new HashSet<Cjenik>();
            this.Rezervacija = new HashSet<Rezervacija>();
        }
    
        public int resurs_ID { get; set; }
        public string naziv { get; set; }
        public string model { get; set; }
        public System.DateTime godina_proizvodnje { get; set; }
        public string slika_url { get; set; }
        public int max_visina { get; set; }
        public double max_teret { get; set; }
        public int radni_sati { get; set; }
        public int status_resursa_ID { get; set; }
    
        public virtual ICollection<Cjenik> Cjenik { get; set; }
        public virtual Paraglajder Paraglajder { get; set; }
        public virtual StatusResursa StatusResursa { get; set; }
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
        public virtual Zrakoplov Zrakoplov { get; set; }
    }
}
