//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public Rezervacija()
        {
            this.Let = new HashSet<Let>();
        }
    
        public int rezervacija_ID { get; set; }
        public int resurs_ID { get; set; }
        public int korisnik_ID { get; set; }
        public System.DateTime datum { get; set; }
        public System.TimeSpan sati_od { get; set; }
        public System.TimeSpan sati_do { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual ICollection<Let> Let { get; set; }
        public virtual Resurs Resurs { get; set; }
    }
}
