//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusResursa
    {
        public StatusResursa()
        {
            this.Resurs = new HashSet<Resurs>();
        }
    
        public int status_resursa_ID { get; set; }
        public string status_resursa { get; set; }
    
        public virtual ICollection<Resurs> Resurs { get; set; }
    }
}
