//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusLeta
    {
        public StatusLeta()
        {
            this.Let = new HashSet<Let>();
        }
    
        public int status_leta_ID { get; set; }
        public string status_leta { get; set; }
    
        public virtual ICollection<Let> Let { get; set; }
    }
}
