//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipDozvole
    {
        public TipDozvole()
        {
            this.Dozvola = new HashSet<Dozvola>();
        }
    
        public int tip_dozvole_ID { get; set; }
        public string tip_dozvole { get; set; }
    
        public virtual ICollection<Dozvola> Dozvola { get; set; }
    }
}
